<?php
/**
 * Product list template
 *
 * @var $block \Gym\JsAuth\Block\Adminhtml\Auth
 */
?>

<main class="page-content" id="appvue">
    <div class="page-columns">
        <div class="admin__old">
            <div class="main-col">
                <!-- ROW para el mensage-->    
                <div class="row">
                    <div id="messages">
                        <div class="messages">
                            <div :class="'message message-' + info.type + ' ' + info.type">
                                <div :data-ui-id="'messages-message-' + info.type">{{ info.msg }}</div>
                            </div>
                        </div>
                     </div>
                </div>                
                <!-- ROW para el contenido-->
                <div class="row dashboard-container">
                    <!-- COL para el video-->
                    <div class="col-m-8 col-l-8 dashboard-secondary">
                        <!-- ROW para el video-->
                        <div class="row">
                            <div class="col-m-10 col-l-10">
                                 <input type="number" v-model="ci" name="ci" id="ci" class="ci-input" placeholder="Entre CI">
                            </div>
                            <div class="col-m-2 col-l-2">
                                <button class="action-primary register-btn" type="submit" title="Registrar" @click="registerWithCi">
                                    Registrar
                                </button>
                            </div>
                        </div>
                    </div>
                    <!-- COL para la respuesta-->
                    <div class="col-m-4 col-l-4">
                        <div class="row">
                            <div class="col-m-12 col-l-12">
                                <!-- respuesta-->
                                <div class="user-identification" v-if="showUserData">
                                    <div class="image-container">
                                        <img class="img-top" v-bind:src="identifiedPerson.image">
                                    </div>
                                    <div class="data">
                                        <ul class="">
                                            <li class="">
                                                <span class="">{{ identifiedPerson.name }}</span>
                                            </li>
                                            <li class="">
                                                <span class="">{{ identifiedPerson.email }}</span>
                                            </li>
                                            <li class="">
                                                <span class="">{{ identifiedPerson.ci }}</span>
                                            </li>
                                        </ul>
                                    </div>
                                    <div class="actions">
                                        <button :disabled="isProcessing" type="button" v-on:click="resetValues" class="btn-ocultar">Ocultar</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
<script type="text/x-magento-init">
    {
        "*": {
            "jsAuth": {
                "assetBaseUrl" : "<?= $block->getAdminBaseUrl() ?>",
                "luxandApiUrl" : "<?= $block->getApiUrl() ?>",
                "luxandToken" : "<?= $block->getApiToken() ?>",
                "registerUrl" : "<?= $block->getUrlRegistry() ?>",
                "timeToMakeRegister" : "<?= $block->getTimeToMakeRegister() ?>"
                }
        }
    }
</script>