<?php
namespace OY\GymBooking\Controller\Adminhtml\Classes;

use Magento\Backend\App\Action;
use Magento\Framework\Exception\LocalizedException;

class Save extends Action
{
    protected $gymClassRepository;

    protected $gymClassFactory;

    public function __construct(
        Action\Context $context,
        \OY\GymBooking\Api\GymClassRepositoryInterface $gymClassRepository,
        \OY\GymBooking\Model\GymClassFactory $gymClassFactory,
        \Magento\Customer\Api\CustomerRepositoryInterface $customerRepository
    ) {
        parent::__construct($context); // TODO: Change the autogenerated stub
        $this->gymClassRepository=$gymClassRepository;
        $this->gymClassFactory=$gymClassFactory;
        $this->customerRepository=$customerRepository;
    }

    public function execute()
    {
        $resultRedirect = $this->resultRedirectFactory->create();
        $data = $this->getRequest()->getPostValue();

        $id = $this->getRequest()->getParam('id');

        if ($data) {
            if ($id) {
                $model = $this->gymClassRepository->getById($id);
            } else {
                $model = $this->gymClassFactory->create();
            }

            if (!$model->getId() && $id!="") {
                $this->messageManager->addErrorMessage(__('This class no longer exists.'));
                return $resultRedirect->setPath('*/classes/');
            }

            try {
                if (isset($data['profesor_id'])) {
                    $customer = $this->customerRepository->getById((int)$data['profesor_id']);
                    $model->setData('profesor_id', (int)$data['profesor_id']);
                    $model->setData('profesor_name', $customer->getFirstname() . ' ' . $customer->getLastname());
                }

                $model->setData('name', $data['name']);
                $model->setData('description', $data['description']);
                if ($data['required_booking']) {
                    $model->setData('required_booking', 1);
                }
                if (isset($data['image']) && isset($data['image'][0]['url'])) {
                    $model->setData('image', $data['image'][0]['url']);
                }

                $this->gymClassRepository->save($model);

                $this->messageManager->addSuccessMessage(__('The class information has been saved.'));

                return $resultRedirect->setPath('*/classes/');
            } catch (LocalizedException $e) {
                $this->messageManager->addError($e->getMessage());
            } catch (\Exception $e) {
                $this->messageManager->addException($e, __('Something went wrong while saving the class information.'));
            }

            return $resultRedirect->setPath('*/classes/');
        }
        return $resultRedirect->setPath('*/classes/');
    }

    protected function _isAllowed()
    {
        return true;
    }
}
