<?php
/**
 * Created by PhpStorm.
 * User: root
 * Date: 05/06/19
 * Time: 05:37 PM
 */
namespace OY\Plan\Model\ResourceModel\Plan;

class Collection extends \Magento\Framework\Model\ResourceModel\Db\Collection\AbstractCollection
{
    protected function _construct()
    {
        $this->_init('OY\Plan\Model\Plan','OY\Plan\Model\ResourceModel\Plan');
    }

    protected function _beforeLoad()
    {
        parent::_beforeLoad(); // TODO: Change the autogenerated stub

        return $this;
    }

    public function toOptionArray()
    {
        $options = [];
        $propertyMap = [
            'value' => 'value_id',
        ];

        foreach ($this as $item) {
            $option = [];
            foreach ($propertyMap as $code => $field) {
                $option[$code] = $item->getData($field);
            }
            $option['label'] = $item->getName();
            $options[] = $option;
        }

        if (count($options) > 0) {
            array_unshift(
                $options,
                ['value' => null, 'label' => ' ']
            );
        }

        return $options;
    }

}
