<?php
namespace OY\GymBooking\Model;

use OY\GymBooking\Api\Data\GymClassDateInterface;

class GymClassDate extends \Magento\Framework\Model\AbstractModel implements GymClassDateInterface
{
    public function __construct(
        \Magento\Framework\Model\Context $context,
        \Magento\Framework\Registry $registry,
        \Magento\Framework\Model\ResourceModel\AbstractResource $resource = null,
        \Magento\Framework\Data\Collection\AbstractDb $resourceCollection = null,
        array $data = []
    )
    {
        parent::__construct($context, $registry, $resource, $resourceCollection, $data);
    }

    protected function _construct()
    {
        parent::_construct(); // TODO: Change the autogenerated stub
        $this->_init('OY\GymBooking\Model\ResourceModel\GymClassDate');
    }
}
