<?php
// @codingStandardsIgnoreFile

/**
 * @var $block \Magento\Catalog\Block\Product\View
 */
$oyHelper         = $this->helper('OY\Catalog\Helper\Data');
?>
<?php
$_product = $block->getProduct();
?>

<div class="cl_count-classes">
    <div class="product-classes-list" role="tablist">
        <div class="collapsible">Clases</div>
        <div class="content">
            <?php
            if($oyHelper->getCountClass($_product->getId())){
                echo '<ul>';
                foreach ($oyHelper->getListClassesId($_product->getId()) as $item){
                    $itemObj = $oyHelper->getClass($item);
                    echo '<li>'.$itemObj->getData('name').'</li>';
                }
                echo '</ul>';
            }
            ?>
        </div>
    </div>

    <script>
        require(['jquery'], function ($) {
            $(function() {
                $( ".collapsible" ).click(function() {
                    $( ".collapsible" ).toggleClass( "active" );
                    $( ".content" ).toggle();
                });
            });
        });
    </script>
</div>
