<?php
// @codingStandardsIgnoreFile

/**
 * @var $block \Magento\Catalog\Block\Product\View
 */
$oyHelper         = $this->helper('OY\Catalog\Helper\Data');
?>
<?php
$_product = $block->getProduct();
?>

<div class="cl_count-classes">
    <div class="product-classes-list" role="tablist">
        <div class="collapsible">Clases</div>
        <div class="content">
            <?php
            if($oyHelper->getCountClass($_product->getId())){
                echo '<ul>';
                foreach ($oyHelper->getListClassesId($_product->getId()) as $item){
                    $itemObj = $oyHelper->getClass($item);
                    echo '<li>'.$itemObj->getData('name').'</li>';
                    echo '<div style="display: inline-block;">';
                    if($itemObj->getData('image')){
                        echo '<div style="float: left; margin-right: 10px; margin-bottom: 10px;"><img width="150" height="150" src="'.$itemObj->getData('image').'"></div>';
                    }
                    echo  '<div style="margin-left: 10px;">'.$itemObj->getData('description').'</div>';
                    echo '<br/>';
                    echo '<strong>Profesor:</strong> '.$itemObj->getData('profesor_name');
                    echo '</div>';
                }
                echo '</ul>';
            }
            ?>
        </div>
    </div>

    <script>
        require(['jquery'], function ($) {
            $(function() {
                $( ".collapsible" ).click(function() {
                    $( ".collapsible" ).toggleClass( "active" );
                    $( ".content" ).toggle();
                });
            });
        });
    </script>
</div>
