<?php

/** @var $block OY\Customer\Block\CustomerPlan\Index */
?>
<?php if ($block->customerVitalicio()): ?>
    <div class="message message-success success">

    </span></div>
<?php else : ?>
    <?php if (count($block->getPlans())): ?>
        <table class="data-grid" >
            <thead>
            <tr>
                <th><?php echo __('Estado') ?></th>
                <th><?php echo __('Tipo') ?></th>
                <th><?php echo __('Fecha de Inicio') ?></th>
                <th><?php echo __('Fecha de Vencimiento') ?></th>
                <th><?php echo __('No. de accesos') ?></th>
                <th><?php echo __('No. de Accesos Habilitados') ?></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($block->getPlans() as $plan): ?>
                <tr>
                    <td>
                        <div class="
                        <?php if ($block->statusPlan($plan['from'], $plan['to'])=='Activo'): ?>
                           <?php echo 'message message-success success' ?>
                        <?php else : ?>
                           <?php echo 'message message-error error' ?>
                        <?php endif; ?>
                        ">
                            <span>
                                <?php echo $block->escapeHtml($block->statusPlan($plan['from'], $plan['to'])) ?>
                            </span>
                        </div>
                    </td>
                    <td><?php echo $block->escapeHtml($block->typePlan($plan['plan'])) ?></td>
                    <td><?php echo $block->escapeHtml($plan['from']) ?></td>
                    <td><?php echo $plan['to'] ?></td>
                    <td>
                        <?php if ($plan['access_enabled']): ?>
                            <?php echo $plan['access_enabled'] ?>
                        <?php else : ?>
                            <?php echo 'Acceso diario' ?>
                        <?php endif; ?>
                    </td>
                    <td>
                        <?php if ($plan['access_number']): ?>
                            <?php echo $plan['access_enabled'] ?>
                        <?php else : ?>
                            <?php echo 'Acceso diario' ?>
                        <?php endif; ?>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    <?php else : ?>
        <div class="message info empty"><span><?= __('Usted no tiene plan de asociado.') ?></span></div>
    <?php endif; ?>
<?php endif; ?>
