<script type="text/javascript">
    require([
        'jquery'
    ], function ($) {
        let date = new Date();

        let day = date.getDate();
        let month = date.getMonth() + 1;
        let year = date.getFullYear();
        let result = '';
        if(month < 10){
            result = `${day}/0${month}/${year}`;
        }else{
            result = `${day}/${month}/${year}`;
        }
       $('.product-custom-option.datetime-picker.input-text').val(result);
    });
</script>