<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Category\View */
$_helper = $this->helper('Gym\Gallery\Helper\GooglePlace');
$images = $_helper->getImagesPath();
$imagesCount = count($images);

?>
<div class="container-gallery-images">
    <div class="gallery <?=$imagesCount?>">
        <?php
        $index = 0;
        foreach ($images as $image) { ?>
            <div class="item">
                <img src="<?php echo $block->getUrl("pub/media/gallery/").$image?>" alt="image" class="gallery-image" data-index="<?=$index++?>" onclick="openModalImage(this)"/>
            </div>
        <?php } ?>
    </div>
</div>

<!-- The Modal -->
<div id="myModal" class="modal">
    <!-- The Close Button -->
    <span id="button-close">&times;</span>
    <!-- Modal Content (The Image) -->
    <div class="container-gallery-viewer" id="gallery-viewer">
        <span class="viewer-prev" onclick="imagesViewerPrev()"></span>
        <img class="modal-content" id="img01">
        <span class="viewer-next" onclick="imagesViewerNext()"></span>
    </div>
</div>

<script type="text/javascript">
    require([
        'jquery',
        'owlcarousel'
    ], function ($, owlcarousel) {

        $('#img01').click(function (evt) {
            evt.stopPropagation();
        });

        $('.viewer-prev').click(function (evt) {
            evt.stopPropagation();
        });

        $('.viewer-next').click(function (evt) {
            evt.stopPropagation();
        });
    });

    var imageSelected = null;
    var imagesCount = 0;

    function openModalImage(elem) {
        imagesCount = <?php echo $imagesCount;?>;
        imageSelected = elem;
        var modal = document.getElementById("myModal");

        // Get the image and insert it inside the modal - use its "alt" text as a caption
        var modalImg = document.getElementById("img01");
        modal.style.display = "flex";
        modalImg.src = elem.src;

        // Get the <span> element that closes the modal
        var span = document.getElementById("button-close");
        var viewer = document.getElementById("gallery-viewer");

        // When the user clicks on <span> (x), close the modal
        span.onclick = function() {
            modal.style.display = "none";
        }
        viewer.onclick = function() {
            modal.style.display = "none";
        }
    }

    function imagesViewerPrev() {
        if (imageSelected.dataset.index > 0) {
            let i = imageSelected.dataset.index - 1;
            let selectImage = document.querySelector(`[data-index="${i}"]`)
            openModalImage(selectImage);
        } else {
            let selectImage = document.querySelector(`[data-index="${imagesCount - 1}"]`);
            openModalImage(selectImage);
        }
    }

    function imagesViewerNext() {
        if (parseInt(imageSelected.dataset.index) + 1 < imagesCount) {
            let i = parseInt(imageSelected.dataset.index) + 1;
            let selectImage = document.querySelector(`[data-index="${i}"]`);
            openModalImage(selectImage);
        } else {
            let selectImage = document.querySelector(`[data-index="0"]`);
            openModalImage(selectImage);
        }
    }

</script>
