<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_BookingSystem
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
$helper = $block->getData('bookingHelper');
$wishlisthelper = $helper->getWishListHelper();
$_productCollection = $block->getItems();
$bookingInfoArray = [];
foreach ($_productCollection as $product) {
    $isBooking = $helper->isBookingProduct($product->getProductId());
    $productUrl = $block->getProductUrl($product);
    $bookingInfoArray[$productUrl]['booking'] = $isBooking;
}
$serializedFormData = $helper->getSerializedString(["bookingInfoArray" => $bookingInfoArray]);
?>
<script type="text/x-magento-init">
    {
        "body": {
            "Webkul_BookingSystem/js/bookingsystem": <?= /* @noEscape */ $serializedFormData ?>
        }
    }
</script>
